parameters:
    pimee_catalog_rule.builder.product.class: 'Basecom\Bundle\RulesEngineBundle\Engine\ProductRuleBuilder'

services:
    pimee_catalog_rule.builder.product:
        class: '%pimee_catalog_rule.builder.product.class%'
        arguments:
            - '@pimee_catalog_rule.denormalizer.product_rule.chained'
            - '@event_dispatcher'
            - '%akeneo_rule_engine.model.rule.class%'
            - '@validator'