parameters:
    basecom.form.type.conditon.class: Basecom\Bundle\RulesEngineBundle\Form\Type\ConditionType
    basecom.form.type.rule.definition.class: Basecom\Bundle\RulesEngineBundle\Form\Type\RuleDefinitionType
    basecom.form.type.action.class: Basecom\Bundle\RulesEngineBundle\Form\Type\ActionType

services:
    basecom.form.type.rule:
        class: '%basecom.form.type.rule.definition.class%'
        arguments:
            - '%akeneo_rule_engine.model.rule_definition.class%'
        tags:
            - { name: form.type, alias: basecom_rule }

    basecom.form.type.condition:
        class: '%basecom.form.type.conditon.class%'
        arguments:
            - '%pimee_catalog_rule.model.product_condition.class%'
            - '@pim_catalog.repository.locale'
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.repository.attribute'
            - '@akeneo_measure.manager'
            - '@pim_catalog.repository.currency'
        tags:
            - { name: form.type, alias: basecom_rule_condition }

    basecom.form.type.action:
        class: '%basecom.form.type.action.class%'
        arguments:
            - '@pim_catalog.repository.locale'
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.repository.attribute'
            - ['add', 'set', 'copy', 'remove']
        tags:
            - { name: form.type, alias: basecom_rule_action }
